<?php
// views/reports/detailed_sales_report.php

// Include authentication check to ensure the user is logged in.
require_once '../../includes/auth_check.php';

// Ensure only 'admin' or 'staff' can access this page for security.
if ($_SESSION['role'] !== 'admin' && $_SESSION['role'] !== 'staff') {
    header("Location: ../dashboard.php"); // Redirect non-authorized users.
    exit();
}

// Include common utility functions (e.g., for general usage, though API now handles DB).
require_once '../../includes/functions.php';

// Start a session if it hasn't been started, for user details like username and role.
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}

// Include the common header file (contains HTML <head> and opening <body> tags, CSS links, etc.).
include '../../includes/header.php';
?>

<div class="dashboard-wrapper">
    <?php
    // Include the sidebar navigation for consistent UI across dashboard pages.
    include '../../includes/sidebar.php';
    ?>
    <div class="main-content" id="main-content">
        <?php $base_url_path = '/capstonefinal'; // Define base URL path for consistency. ?>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top px-3 custom-navbar-top no-print">
            <div class="container-fluid">
                <!-- Toggle button for mobile sidebar. -->
                <button id="sidebarToggle" class="btn btn-outline-light d-lg-none me-3" type="button">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Toggle button for desktop sidebar. -->
                <button id="sidebarToggleDesktop" class="btn btn-outline-light d-none d-lg-block me-3" type="button">
                    <i class="fas fa-bars"></i> <!-- Font Awesome icon for a menu bar. -->
                </button>
                <a class="navbar-brand" href="#">POS System</a>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0"></ul>
                    <ul class="navbar-nav ms-auto">
                        <!-- Display welcome message with username and role from session. -->
                        <li class="nav-item d-flex align-items-center">
                            <span class="nav-link text-white me-2">Welcome, <?php echo htmlspecialchars($_SESSION["username"] ?? 'Guest'); ?> (<?php echo htmlspecialchars($_SESSION["role"] ?? 'N/A'); ?>)</span>
                        </li>
                        <!-- Logout button, using base URL path for consistency. -->
                        <li class="nav-item">
                            <a class="nav-link btn btn-danger btn-sm text-white" href="<?php echo $base_url_path; ?>/logout.php">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div id="printableArea" class="container-fluid dashboard-page-content mt-5 pt-3">
            <div class="print-header">
                <h3>Sales Report</h3>
                <!-- Date range and generation info will be updated by JS or remain placeholder for print. -->
                <p id="reportDateRange">Date Range: Loading...</p>
                <p>Generated by: <?php echo htmlspecialchars($_SESSION["username"] ?? 'N/A'); ?> on <?php echo date('Y-m-d H:i:s'); ?></p>
            </div>

            <!-- Alerts will now be handled by JavaScript. This PHP block is removed from here. -->

            <div class="card mb-4 no-print">
                <div class="card-header">
                    Filter Sales Report
                </div>
                <div class="card-body">
                    <!-- Form for filtering sales data. Submission handled by JavaScript. -->
                    <form id="filterForm" class="row g-3 align-items-end">
                        <div class="col-md-3">
                            <label for="start_date" class="form-label">Start Date:</label>
                            <input type="date" class="form-control" id="start_date" name="start_date" value="" required>
                        </div>
                        <div class="col-md-3">
                            <label for="end_date" class="form-label">End Date:</label>
                            <input type="date" class="form-control" id="end_date" name="end_date" value="" required>
                        </div>
                        <div class="col-md-3">
                            <label for="records_per_page" class="form-label">Records per page:</label>
                            <select class="form-select" id="records_per_page" name="records_per_page">
                                <!-- Options will be dynamically set or default to 10-100 -->
                                <option value="10">10</option>
                                <option value="20">20</option>
                                <option value="30">30</option>
                                <option value="40">40</option>
                                <option value="50">50</option>
                                <option value="60">60</option>
                                <option value="70">70</option>
                                <option value="80">80</option>
                                <option value="90">90</option>
                                <option value="100">100</option>
                            </select>
                        </div>
                        <div class="col-md-3">
                            <button type="submit" class="btn btn-primary w-100">Apply Filter</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="mb-4 text-end no-print">
                <button class="btn btn-secondary" onclick="printReportInNewWindow()"><i class="fas fa-print"></i> Print Report</button>
            </div>

            <div class="card mb-4">
                <div class="card-header">
                    Summary for Selected Period
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <div class="summary-box bg-success text-white text-center p-3 rounded shadow-sm">
                                <h4>Total Sales Amount:</h4>
                                <h3 id="totalSalesAmount">Loading...</h3>
                            </div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <div class="summary-box bg-info text-white text-center p-3 rounded shadow-sm">
                                <h4>Total Items Sold:</h4>
                                <h3 id="totalItemsSold">Loading...</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card">
                <div class="card-header">
                    Detailed Sales Transactions
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover" id="salesTable">
                            <thead>
                                <tr>
                                    <th>Sale ID</th>
                                    <th>Date</th>
                                    <th>Cashier</th>
                                    <th>Items Sold</th>
                                    <th>Total Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                <!-- Sales data will be loaded dynamically by public/js/detailed_sales_report_script.js -->
                                <tr>
                                    <td colspan="5" class="text-center">Loading sales data...</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <!-- Pagination controls will be built dynamically by JavaScript -->
                    <nav id="paginationNav" aria-label="Sales Pagination" class="mt-4 no-print">
                        <!-- Pagination links will be injected here by JavaScript -->
                    </nav>

                </div>
            </div>
        </div>
    </div>
</div>

<div class="overlay" id="overlay"></div>
<!-- Font Awesome for icons. Using protocol-relative URL to avoid CORS issues if page is HTTP. -->
<script src="//kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
<!-- Bootstrap 5 JavaScript bundle (includes Popper.js) -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<!-- Your main.js for global JavaScript functionalities (e.g., sidebar toggling) -->
<script src="../../public/js/main.js"></script>
<!-- NEW: Include the specific JavaScript for detailed sales reports to handle AJAX operations -->
<script src="../../public/js/detailed_sales_report_script.js"></script>
</body>
</html>